### ISSUE TITLE
 bad response Unauthorized 401 (https://rubygems.pkg.github.com/compeon/specs.4.8.gz)

### ISSUE THREAD

**Issue by rgaufman** [COMPEON/rails-assets-mirror#1]
I'm trying to follow the install instructions but getting a 401 error, any ideas? < 

```$ gem install rails-assets-jquery --version "3.4.1" --source "https://rubygems.pkg.github.com/compeon"
ERROR:  Could not find a valid gem 'rails-assets-jquery' (= 3.4.1), here is why:
          Unable to download data from https://rubygems.pkg.github.com/compeon/ - bad response Unauthorized 401 (https://rubygems.pkg.github.com/compeon/specs.4.8.gz)
ERROR:  Possible alternatives: rails-asset-jqueryui, rails-asset-jqgrid, rails-assets-tether, rails-assets-cdn, rails-assets-enzyme, rails_assets, rails_autosize_jquery, rails-assets-bundler, rails3_sequel, rails_adserver
```

**Comment by lagr** [comment]
Hello @rgaufman, this repository is merely a mirror that permits our organization ([COMPEON](https://github.com/COMPEON)) to retrieve several rails-assets gems reliably from our own package repository at GitHub. That repository requires a privileged access token to download. We do not maintain them and will remove them altogether in foreseeable future. I'd thus advise you to install the required gems from rails-assets.org directly. :-)
